const gakuhub = `<h1>gakuhub</h1><div class="body"><p>gakuhub is a personal side project that I started aimed to provide a platform for internationals students within Japan to connect with each other. When I first started looking into completing my Bachelor’s degree in Japan, I found that there was a lack of first-hand resource available for me to consult with and see if is was for me. Even after getting to university in Japan, I found that there was little infrastructure available to connect the international students of different year groups.</p><p>I want this service to become a gateway for prospective students to obtain information and consult with current students on their experiences. Even after arriving in Japan, provide a platform to which anyone may seek help whether to setup everything they need, deal with the language barrier most encounter on arrival or simply to find new people and have a community to connect with.</p><p>The frameworks used for this project are:</p><ul><li>Front-end: Node.js with Vue CLI - webpack</li><li>Back-end: Loopback (Node.js) Express Server</li><li>Database: MongoDB</li></ul></div>`;
const portfolio = `<h1>Portfolio Site</h1><div class="body"> <p>I want this project to be more than just a portfolio site. I want this to be a reflection what I am capable of. Everything from the design to custom animations has been created by me on top of the Vue framework. This will be a project that I will constantly be working on and adding new features to in my free time so check back every so often to see what’s new!</p><p>As of now, the site is still fairly bare-bones but I would like to keep expanding on top of it including:</p><ul><li>Blog</li><li>Small tools</li><li>Updates as I keep developing my skills so that this will be a true reflection of my work</li></ul><h5>Planned to support more features:</h5><p>Vue CLI with Server-side Rendering served on a Express server<ul><li>Vue.js</li><ul><li>Vue Router</li><li>Vuex</li><li>Node.js Backend with MySQL database</li></ul></ul></p></div>`;
const gazeKey = `<h1>gaze-key</h1><div class="body"><p>The ability to input text in an electronic device is one of the most powerful interaction methods available to a user. While traditional keyboards have asserted themselves as the primary hands-on input method on almost all commercial computer systems, there is yet to be an outstanding method for hands-free input, more specifically in the field utilizing eye tracking. There has been a lot of research within this field, most notably in assisting individuals with disabilities, and has improved with alongside the advancement of eye tracking technology. As we head more towards the world of filled with Virtual Reality (VR) or perhaps more notably, Artificial Reality (AR), an efficient hands-free system of text input becomes ever so important to further unlock potential interactions using these technologies.</p><p>In this research, I aim to create an input system using pure eye tracking that is easy and efficient to use within the graphical interface provided by a head mounted displays (HMD). The main scenario this research is based upon is the use within a head-up display (HUD) from a device such as glasses, that is connected with a smartphone to provide basic notification and interactions without physically interacting with the smartphone itself. There is not expectation for such a method to rival traditional keyboards but has the goal to allow simple interactions such as text messaging or inputting keywords for a search.</p></div>`;
const repro = `<h1>Repro Web SDK</h1><div class="body"><p>I work as one of the core members in developing the Repro Web SDK which enables user activity on web pages to be tracked with the Repro marketing service. The Web SDK was launched in December 2018 and is continuing to be developed to form one of the pillars of Repro. The SDK is written in a mix of JavaScript and TypeScript and uses a variety of testing frameworks such as Karma + Jasmine for unit testing and Testcafe + Browserstack for E2E and integration tests.</p><a class="button" href="https://repro.io/jp/products/web/" target="_blank">More about Repro Web Service (Japanese only)</a><h4>About Repro</h4><p>Repro is a easy to use analysis and marketing service that is widely used in 50+ countries and has notable domestic customers such as KDDI, TV Tokyo and DeNA. It provides analytic tools and statistics such as user retention, access, funnelling, etc and allows targeted marketing to an audience that meet the set criteria. With Repro, you can view screen recording of actual users and send out push notifications and messages to users through the web interface.</p><a class="button" href="https://repro.io/en/" target="_blank">More about Repro</a></div>`;

export default {
  state: {
    templates: [
      repro,
      gazeKey,
      gakuhub,
      portfolio,
    ]
  },
  mutations: {

  },
  actions: {

  },
}
